# Generated by Django 3.2 on 2021-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stationinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationname', models.CharField(blank=True, max_length=255, null=True)),
                ('writedbtime', models.DateTimeField(blank=True, null=True)),
                ('diskfree', models.PositiveBigIntegerField(blank=True, null=True)),
                ('devtemp', models.IntegerField(blank=True, null=True)),
                ('weidu', models.CharField(blank=True, max_length=32, null=True)),
                ('jingdu', models.CharField(blank=True, max_length=32, null=True)),
                ('gpslock', models.CharField(blank=True, max_length=4, null=True)),
                ('gpssatenum', models.PositiveIntegerField(blank=True, null=True)),
                ('fastvolta', models.IntegerField(blank=True, null=True)),
                ('trigerdatalen', models.PositiveIntegerField(blank=True, null=True)),
                ('filetouploadnum', models.PositiveIntegerField(blank=True, null=True)),
                ('hardver', models.CharField(blank=True, max_length=8, null=True)),
                ('softver', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'db_table': 'stationinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waveinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigertime', models.DateTimeField()),
                ('trigerdotsecond', models.PositiveIntegerField(blank=True, null=True)),
                ('stationname', models.CharField(db_collation='utf8_general_ci', max_length=255)),
                ('fieldtype', models.CharField(db_collation='utf8_general_ci', max_length=5)),
                ('fieldseq', models.PositiveSmallIntegerField()),
                ('wavetype', models.CharField(db_collation='utf8_general_ci', max_length=8)),
            ],
            options={
                'db_table': 'waveinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveinfoIc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigertime', models.DateTimeField()),
                ('trigerdotsecond', models.PositiveIntegerField(blank=True, null=True)),
                ('stationname', models.CharField(max_length=255)),
                ('fieldseq', models.PositiveSmallIntegerField()),
                ('wavetype', models.CharField(max_length=16)),
                ('peaktime', models.CharField(max_length=30)),
                ('peakvalue', models.IntegerField(blank=True, null=True)),
                ('polar', models.IntegerField(blank=True, null=True)),
                ('riseedge', models.FloatField(blank=True, null=True)),
                ('sliceindex', models.PositiveIntegerField(blank=True, null=True)),
                ('writedbtime', models.DateTimeField()),
                ('slicefile', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'waveinfo_ic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveinfoNb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigertime', models.DateTimeField()),
                ('trigerdotsecond', models.PositiveIntegerField(blank=True, null=True)),
                ('stationname', models.CharField(max_length=255)),
                ('fieldseq', models.PositiveSmallIntegerField()),
                ('wavetype', models.CharField(max_length=16)),
                ('peaktime', models.CharField(max_length=30)),
                ('peakvalue', models.IntegerField(blank=True, null=True)),
                ('polar', models.IntegerField(blank=True, null=True)),
                ('riseedge', models.FloatField(blank=True, null=True)),
                ('sliceindex', models.PositiveIntegerField(blank=True, null=True)),
                ('writedbtime', models.DateTimeField()),
                ('slicefile', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'waveinfo_nb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveinfoPb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigertime', models.DateTimeField()),
                ('trigerdotsecond', models.PositiveIntegerField(blank=True, null=True)),
                ('stationname', models.CharField(max_length=255)),
                ('fieldseq', models.PositiveSmallIntegerField()),
                ('wavetype', models.CharField(max_length=16)),
                ('peaktime', models.CharField(max_length=30)),
                ('peakvalue', models.IntegerField(blank=True, null=True)),
                ('polar', models.IntegerField(blank=True, null=True)),
                ('riseedge', models.FloatField(blank=True, null=True)),
                ('sliceindex', models.PositiveIntegerField(blank=True, null=True)),
                ('writedbtime', models.DateTimeField()),
                ('slicefile', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'waveinfo_pb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaveinfoRs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigertime', models.DateTimeField()),
                ('trigerdotsecond', models.PositiveIntegerField(blank=True, null=True)),
                ('stationname', models.CharField(max_length=255)),
                ('fieldseq', models.PositiveSmallIntegerField()),
                ('wavetype', models.CharField(max_length=16)),
                ('peaktime', models.CharField(max_length=30)),
                ('peakvalue', models.IntegerField(blank=True, null=True)),
                ('polar', models.IntegerField(blank=True, null=True)),
                ('riseedge', models.FloatField(blank=True, null=True)),
                ('sliceindex', models.PositiveIntegerField(blank=True, null=True)),
                ('writedbtime', models.DateTimeField()),
                ('slicefile', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'waveinfo_rs',
                'managed': False,
            },
        ),
    ]
